### ISSUE TITLE
Improve hiera support

### ISSUE THREAD

**Issue by rgarrigue** [biemond/biemond-wildfly#163]
I'm not sure what one can setup through hiera wildfly:: or wildfly::param. Some things maybe, not all for sure since I spent some time trying.

Most importantly I'ld recommand documenting what is or isn't possible. One class example, one hiera example if possible. Or at least a "Hiera : nothing yet / ever" chapter in the doc.

Crayfishx's firewalld module is a good example of what I'm thinking about : https://forge.puppet.com/crayfishx/firewalld

**Comment by jairojunior** [comment]
We don't support creating resources from Hiera at all. If you want to do something like this, you should consider do it in your profiles:

```puppet
profiles::wildfly::datasource($resources) {
  create_resources('wildfly::datasources::datasource`, $resources)
}
```

```yaml
profiles::wildfly::datasource::resources:
- MyDS
  config: 
    datasource_property1: value
    datasource_property2: value
- AnotherDS
  config:
    datasource_property1: value
    datasource_property2: value
```

It's a raw untested example just to give you the idea.

Our only support to Hiera is through Automatic Parameter Lookup: https://docs.puppet.com/hiera/3.2/puppet.html#automatic-parameter-lookup
