### ISSUE TITLE
Idempotence issue ?

### ISSUE THREAD

**Issue by rgarrigue** [biemond/biemond-wildfly#164]
Hi

Shortly said, a first `vagrant up` run my VM fine, all puppet provisionning is green. I follow up with a `vagrant provision` (and dozen other for what matter), I end up with this error 

```
Error: Failed with: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:"=>{"Operation step-1"=>"WFLYCTL0201: Unknown attribute 'xa-datasource-class'"}} for {"address":[],"operation":"composite","steps":[{"address":[{"subsystem":"datasources"},{"data-source":"DatasourceLiferayXA"}],"operation":"write-attribute","name":"xa-datasource-class","value":"org.postgresql.xa.PGXADataSource"},{"address":[{"subsystem":"datasources"},{"data-source":"DatasourceLiferayXA"}],"operation":"write-attribute","name":"xa-datasource-properties","value":{"url":{"value":"jdbc:postgresql://localhost/liferay"}}}],"operation-headers":{}}
```

Scrolling up, I see that same step got the all green before

```
Notice: /Stage[main]/Profiles::Wildfly/Wildfly::Datasources::Datasource[DatasourceLiferayXA]/Wildfly::Resource[/subsystem=datasources/data-source=DatasourceLiferayXA]/Wildfly_resource[/subsystem=datasources/data-source=DatasourceLiferayXA]/ensure: created
```

I'm at a loss here, any idea why the behavior might change ? Maybe that's about wildfly's CLI, any bug for version 10.1.0 I should be aware off ? 

If you want some details, here is the piece of hiera

```
...
# Drivers et datasources
profiles::wildfly::drivers:
  'DriverPostgreSQL':
    driver_name: 'postgresql'
    driver_module_name: 'org.postgresql' # Doit matcher avec le module
    driver_xa_datasource_class_name: 'org.postgresql.xa.PGXADataSource'
profiles::wildfly::datasources:
  'DatasourceLiferay':
    config:
      driver-name: postgresql
      connection-url: 'jdbc:postgresql://localhost/liferay'
      jndi-name: 'java:jboss/datasources/liferay'
      user-name: 'liferay'
      password: '12345678liferay'
      max-pool-size: '50'
profiles::wildfly::xadatasources:
  'DatasourceLiferayXA':
    config:
      driver-name: postgresql
      connection-url: 'jdbc:postgresql://localhost/liferay'
      jndi-name: 'java:jboss/datasources/liferayXA'
      user-name: 'liferay'
      xa-datasource-class: 'org.postgresql.xa.PGXADataSource'
      xa-datasource-properties:
        url:
          value: 'jdbc:postgresql://localhost/liferay'
...
```

And here is the puppet

```
  anchor { 'drivers': }

  if($datasources) {
    create_resources(
      '::wildfly::datasources::datasource',
      $datasources,
      {
        require => Anchor['drivers'],
        before => Anchor['datasources'],
      },
    )
  }

  anchor { 'datasources': }

  if($xadatasources) {
    create_resources(
      '::wildfly::datasources::datasource',
      $xadatasources,
      {
        require => Anchor['datasources'],
        before => Anchor['xadatasources'],
      },
    )
  }

  anchor { 'xadatasources': }

  if($deployments) {
    create_resources(
      '::wildfly::deployment',
      $deployments,
      {
        require => Anchor['xadatasources'],
        before => Anchor['deployments'],
      },
    )
  }

  anchor { 'deployments': }
```
